# Generated by Django 5.1.5 on 2025-01-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsideTemp',
            fields=[
                ('timestamp', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('battery_level', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='OutsideTemp',
            fields=[
                ('timestamp', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('weather', models.CharField(max_length=100)),
            ],
        ),
    ]
